development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:018d806a418edd859515db6599e8d223@dory.redistogo.com:10178/
  channel_prefix: ClimbOn_production
